---
title: "Leam Howe - Curriculum Vitae"
format:
  html:
    toc: true
    css: cv.css
  pdf:
    author: Leam Howe
    # pdf-engine: weasyprint
    pdf-engine: pdflatex
    css: cv.css
format-links: [pdf]
---

<!-- ---
title: "Curriculum Vitae"
format:
  html:
    toc: true
  pdf:
    author: "Your Name"
    pdf-engine: pdflatex
--- -->

::: {.content-visible when-format="html"}
[Download my CV as a PDF](cv.pdf){.btn .btn-primary}
:::

<!-- Important: Replace all template content, especially contact details, with your own information. -->

<!-- Important: When updating your email address, remember to change both the "text" (visible text) and the "link" (underlying hyperlink) fields. -->


<!-- Important: Replace all template content, especially contact details, with your own information. -->

<!-- Important: When updating your email address, remember to change both the "text" (visible text) and the "link" (underlying hyperlink) fields. -->

<!-- # Leam Howe -->
PhD Researcher, University of Edinburgh, SENSE Earth Observation CDT

## Research Interests
*PhD researcher in Environmental science with a particular focus on remote sensing and Earth observation from space; keen on utilising machine learning to capitalise on these rapidly expanding datasets. Developing a career in academia whilst maintaining relationships with industry partners and working on outreach projects to improve public communication of climate science. Partial to mountains, snow, and coffee.*

## Education

**2022 - Present: University of Edinburgh, PhD NERC SENSE Earth Observation CDT**

Remote sensing and modelling of mountain snow patches. Using novel high-resolution remote sensing and meteorological modelling to improve our understanding of the climate sensitivity of mountain snow.

**2021 – 2022: University of Leeds, MRes Climate and Atmospheric Science (Distinction)**
Research project applying machine learning techniques to efficiently identify anomalous behaviour in SAR ice velocity data.

**2015 – 2019: University of Nottingham, MSci Physics (2:1 Hons)**
Two first-class research projects and gained valuable coding, statistical analysis, and communication skills.


## Publications in preparation

**Howe, L.**, Essery, R., Crowley E. J., SPUN: Deep learning for continuous snow cover fraction retrieval in marginal environments. *To be submitted to HESS in Spring 2026.*

## Non Peer-reviewed Publications
**Howe, L.** (2026) The Death of Scotland’s Zombie Glaciers. *Published in RSGS’s ‘The Geographer’.*

## Software & Data Products

* fieldwork data 
* SPUN snow maps
* Highest resolution snow persistence maps of Scotland retrieved from Sentinel-2 with machine learning.

## Professional Experience

**Cooking Engineer Intern**
  ~ Microwavesoft
  ~ 07/2021 - Present

- Developed an innovative, versatile cooking methodology applicable across diverse ingredients, incorporating and improving upon recent culinary trends
- Created a streamlined cream of mushroom soup recipe, achieving results comparable to complex state-of-the-art techniques through a novel mushroom-cutting approach; published in NIPS 2099 (see [~P1])
- Designed a specialized cooking pan that enhanced research efficiency for team members


**Engineering Chef Intern**
  ~ University of California, Berkebake
  ~ 08/2020 - Present

- Developed a precise mapo tofu quality assessment technique using thermometer-based measurements
- Invented a rapid stir-frying algorithm for tofu cooking, replacing vague instructions like "add as much as you can" with specific hot sauce measurements; published in CVPR 2077 (see [~P2])
- Outperformed SOTA cooking methods in both efficiency and quality across experiments with popular tofu types


**Student Chef**
  ~ Cabbage Melon University
  ~ 03/2020 - 06/2020

- Developed an innovative mapo tofu consumption framework utilizing a spoon-chopstick combination
- Engineered a filtering method for tofu dataset creation, inspired by bean grinding techniques
- Established two new metrics for evaluating eating plan novelty and diversity
- Significantly surpassed existing methods and baselines in diversity, novelty, and coherence


**Research Chef Intern**
  ~ Snapchopstick
  ~ 07/2018 - 08/2018

- Designed two novel sandwiches by repurposing breads and meat from traditional bacon cheeseburgers, maximizing resource efficiency
- Leveraged structure duality to boost cooking speed for two complementary tasks based on shared ingredients
- Surpassed strong baselines on QWE'15 and ASDF'14 dataset


## Grants

**Global Change Institute small grants - £850**
Funded to set up a new 'Machine Learning for Geoscience and Earth Observation (ML4GEO)' research group 

**NERC Diversifying the Pipline** (2024)

**SENSE outreach funding - £10,000**

Awarded to the SatSchool outreach project from the SENSE CDT to contribute to continued development, refinement, and delivery of outreach materials.

**SAGES Small Grant Scheme for Scottish fieldwork - £500** (2024)

Fieldwork in the Cairngorms, Scotland, contributing to my PhD project investingating the reflective properties of Scottish snow using a sensor matched to Sentinel-2 and mounted on the DJI M350 drone. 

**SAGES Small Grant Scheme - £850**

Awarded to run a workshop to promote engagement with the SatSchool outreach project and developed new ideas for outreach materials.

**Ogden Trust Physics Education Grant - £5,000** (2022)

Grant awarded to SatSchool Outreach projec to align outreach resources with the KS3 Physics curriculum.

**SENSE Earth Observation CDT Studentship - £66,000** (2022 - Present)

PhD fully funded by the UKRI Natural Environment Research Council.


## Awards & Prizes

**SENSE Student Award for Outreach**, 
  ~ 2026

**SENSE Industry Symposium prize for soical**, awarded for efforts to develop and promote a collaborative and social community within the SENSE CDT.
  ~ 2023

## Oral Presentations

**SAGES AI/ESM Fora Meeting, October 2025**
Invited speaker. 

**Living Planet Symposium, Vienna July 2025**

**SLF External Seminar, Jan 2025**

Invited speaker

**National Earth Observation Conference, York Sep 2024**

**SAGES Annual Science Meeting, May 2024**


## Poster Presentations

**University of Cambridge ICCS NERC workshop on Bayesian Machine Learning as a tool for Climate Scientists, April 2024**

**8th General Assembly of the International Union of Geodesy and Geophysics (IUGG), July 11-20, 2023 in Berlin, Germany.**

**Scottish Alliance for Geoscience & Society (SAGES) ASM 2023.**

## Presentation Contributions

Essery, R., Nemec, J., **Howe, L.**, Schwaizer, G., and Nagler, T.: Gap filling satellite snow cover for mountain catchments, EGU General Assembly 2025, Vienna, Austria, 27 Apr–2 May 2025, EGU25-6832, https://doi.org/10.5194/egusphere-egu25-6832, 2025.


## Fieldwork Experience



## Teaching Experience


## Outreach & Volunteering 

* 

## Additional Relevant Experience

ENVEO IT GmbH (October – December 2023)
ENVEO is an IT company developing satellite data product of the cryosphere. I completed a 3-month research placement working with their snow products. This gave me valuable experience of coding protocols in industry whilst working with geospatial data and an insight into the business model of an academic spin-off companies
Astrium UK (October 2013)
EADS aerospace manufacturer (notably developed Cryosat and Sentinel satellites). Shadowed engineers developing satellites and spacecraft.

## Qualifications

* Qualified drone pilot, A2 CofC



## Professional Societies

Scottish Alliance for Geoscience & Society (SAGES)

Royal Geographical Society (RGS)

Institute of Physics (IOP)

## Hobbies & Interests

**Outdoors/Sports:** Lover of the outdoors. Often in the mountains hiking, climbing, running, or cycling. Working towards my Mountain Leader qualifications. I have achieved my Advanced Open Water Diver and Underwater Digital Photographer PADI qualifications.

**Art (photography, sketching, painting):** I have a passion for photography and rarely travel anywhere without my camera. I enjoy sketching and watercolour, often in inspiring places.

**Music:** I have achieved grade 7 piano and grade 6 guitar.

## References 

**Prof Cathryn Birch**, Professor, School of Earth and Environment, University of Leeds,
C.E.Birch@leeds.ac.uk, +44(0)113 343 9831

**Prof Anna Hogg**, Professor, School of Earth and Environment, University of Leeds,
A.E.Hogg@leeds.ac.uk, +44(0)113 343 5842.

**Prof Richard Essery**, Professor, School of Geosciences, University of Edinburgh,
richard.essery@ed.ac.uk, +44(0)131 651 9093.

**Dr Steven Bamford**, Associate Professor, School of Physics & Astronomy, University of Nottingham, steven.bamford@nottingham.ac.uk. +44 (0)1157 484054.
